# Generated by Django 3.2 on 2021-04-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this post should be treated as active. Unselect this instead of deleting posts.', verbose_name='active')),
            ],
        ),
    ]
